### ISSUE TITLE
ConnectionError: Handshake status 401 Unauthorized

### ISSUE THREAD

**Issue by CodeDuoGun** [pangxiaobin/ImageToTextProject#1]
Quit the server with CONTROL-C.

[16/Oct/2024 13:58:31] "GET / HTTP/1.1" 200 4438
[16/Oct/2024 13:58:31] "GET /static/layui/css/layui.css HTTP/1.1" 304 0
[16/Oct/2024 13:58:31] "GET /static/layui/layui.js HTTP/1.1" 304 0
[16/Oct/2024 13:58:36] "GET /upload/ HTTP/1.1" 200 6529
[16/Oct/2024 13:58:54] "GET /static/layui/font/iconfont.woff2?v=282 HTTP/1.1" 304 0
start predicting
end predicting, use time: 0.35552120208740234
Traceback (most recent call last):
  File "/home/shiyou/TXD/ImageToTextProject/app/views.py", line 67, in upload_view
    text = llm_model_instance(model_name=model_name).generate(prompt)
  File "/home/shiyou/TXD/ImageToTextProject/llm_model/predict.py", line 82, in generate
    response = self.llm.invoke(prompt)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 276, in invoke
    self.generate_prompt(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 633, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 803, in generate
    output = self._generate_helper(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 670, in _generate_helper
    raise e
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 657, in _generate_helper
    self._generate(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1322, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_community/llms/sparkllm.py", line 148, in _call
    for content in self.client.subscribe(timeout=self.request_timeout):
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_community/llms/sparkllm.py", line 376, in subscribe
    raise ConnectionError(content["error"])
ConnectionError: Handshake status 401 Unauthorized -+-+- {'date': 'Wed, 16 Oct 2024 05:58:55 GMT', 'content-type': 'application/json; charset=utf-8', 'connection': 'keep-alive', 'content-length': '76', 'server': 'kong/1.3.0'} -+-+- b'{"message":"HMAC signature cannot be verified: fail to retrieve credential"}'

Internal Server Error: /upload/
[16/Oct/2024 13:58:55] "POST /upload/ HTTP/1.1" 500 311
start predicting
end predicting, use time: 0.08563375473022461
Traceback (most recent call last):
  File "/home/shiyou/TXD/ImageToTextProject/app/views.py", line 67, in upload_view
    text = llm_model_instance(model_name=model_name).generate(prompt)
  File "/home/shiyou/TXD/ImageToTextProject/llm_model/predict.py", line 82, in generate
    response = self.llm.invoke(prompt)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 276, in invoke
    self.generate_prompt(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 633, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 803, in generate
    output = self._generate_helper(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 670, in _generate_helper
    raise e
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 657, in _generate_helper
    self._generate(
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 1322, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_community/llms/sparkllm.py", line 148, in _call
    for content in self.client.subscribe(timeout=self.request_timeout):
  File "/home/shiyou/anaconda3/envs/dalle/lib/python3.10/site-packages/langchain_community/llms/sparkllm.py", line 376, in subscribe
    raise ConnectionError(content["error"])
ConnectionError: Handshake status 401 Unauthorized -+-+- {'date': 'Wed, 16 Oct 2024 05:59:29 GMT', 'content-type': 'application/json; charset=utf-8', 'connection': 'keep-alive', 'content-length': '76', 'server': 'kong/1.3.0'} -+-+- b'{"message":"HMAC signature cannot be verified: fail to retrieve credential"}'

Internal Server Error: /upload/

i met the question above on runing this project, can someone tell me why?

**Comment by pangxiaobin** [comment]
To view the logs, there is an issue with the Xunfei's Spark model account.
Please verify the three values configured in the .env file:
IFLYTEK_SPARK_APP_ID=your_app_id
IFLYTEK_SPARK_API_KEY=your_api_key
IFLYTEK_SPARK_API_SECRET=your_api_secret
